# Prerequisites:
# - Set a SNYK_TOKEN in the pipelines secrets
# - Install the SARIF viewer extension from here: https://marketplace.visualstudio.com/items?itemName=sariftools.scans&targetId=bf3858e2-f2d0-4e06-962a-2107402a1234

# NOTE: Change this to a different pool to run the scripts.
pool: sebsnyk.pool 

steps:
  - checkout: self

  # .. your instructions on building the app or preparing the repository

  # install & prepare snyk
  - script: |
      npm install -g snyk snyk-to-html -g
      snyk auth $(SNYK_TOKEN)
    displayName: 'snyk install & auth'

  # snyk code
  - script: snyk code test --sarif-file-output=CodeAnalysisLogs/snyk-code.sarif
    continueOnError: true
    displayName: 'snyk code'

  # snyk open source
  - script: snyk test --sarif-file-output=CodeAnalysisLogs/snyk-open-source.sarif
    continueOnError: true
    displayName: 'snyk'

  # snyk container
  - script: snyk container test sebsnyk/juice-shop --file=Dockerfile --sarif-file-output=CodeAnalysisLogs/snyk-container.sarif
    continueOnError: true
    displayName: 'snyk container'

  # snyk iac
  - script: snyk iac test --sarif-file-output=CodeAnalysisLogs/snyk-iac.sarif
    continueOnError: true
    displayName: 'snyk iac'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: CodeAnalysisLogs"
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)/CodeAnalysisLogs
      ArtifactName: CodeAnalysisLogs
