# Runs 4 Snyk Products (Code, Open Source, Container, IaC)
# Outputs the results to the pipeline

# Prerequisites:
# - Set a SNYK_TOKEN in the pipelines secrets
# - Install the HTML viewer extension
#   https://marketplace.visualstudio.com/items?itemName=JakubRumpca.azure-pipelines-html-report

# NOTE: Change this to a different pool to run the scripts.
pool: sebsnyk.pool 

steps:
  - checkout: self

  # .. your instructions on building the app or preparing the repository

  # install & prepare snyk
  - script: |
      npm install -g snyk snyk-to-html
      mkdir html
      snyk auth $(SNYK_TOKEN)

      # explicitly allow scripts to continue if errors occur
      set +e
    displayName: 'snyk install & auth'

  # snyk code
  - script: |
      snyk code test --sarif-file-output=results.sarif
      RESULT=$?
      snyk-to-html -o html/results-code.html < results.sarif
    continueOnError: true
    displayName: 'snyk code'

  # # snyk open source
  # - script: snyk test --sarif-file-output=CodeAnalysisLogs/snyk-open-source.sarif
  #   continueOnError: true
  #   displayName: 'snyk open source'

  # # snyk container
  # # NOTE: Change this to your container name
  # - script: snyk container test sebsnyk/juice-shop --file=Dockerfile --sarif-file-output=CodeAnalysisLogs/snyk-container.sarif
  #   continueOnError: true
  #   displayName: 'snyk container'

  # # snyk iac
  # - script: snyk iac test --sarif-file-output=CodeAnalysisLogs/snyk-iac.sarif
  #   continueOnError: true
  #   displayName: 'snyk iac'

  # publish the results
  - task: PublishHtmlReport@1
    displayName: 'Publish HTML results'
    inputs:
      reportDir: 'html'
