# Prerequisites
# Set a SNYK_TOKEN in the pipelines secrets


# pool:
#   # todo: set this you your own pool as applicable.
#   vmImage: ubuntu-latest

pool: sebsnyk.pool

steps:
  - checkout: self
  - task: NodeTool@0
    displayName: Use Node version 16
    inputs:
      versionSpec: 16
  # ... build your projects here, if needed.
  # - bash: |
  #     npm install -g snyk snyk-to-html
  #     snyk auth $SNYK_TOKEN
  # # - task: CmdLine@2
  # #   displayName: Snyk static code analysis
  # #   inputs:
  # #     script: >-
  # #       /home/vsts/work/_temp/snyk-linux auth $(SNYK_TOKEN)
        
  # #       mkdir CodeAnalysisLogs
        
  # #       /home/vsts/work/_temp/snyk-linux code test --severity-threshold=low --sarif-file-output=CodeAnalysisLogs/snyk-code.sarif
        
  # #       exit 0
  - script: |
      npm install -g snyk snyk-to-html -g
      snyk auth $(SNYK_TOKEN)
    displayName: 'snyk install & auth'
  - script: |
      snyk test --sarif-file-output=CodeAnalysisLogs/snyk-open-source.sarif
    continueOnError: true
    displayName: 'snyk test'
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: CodeAnalysisLogs"
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)/CodeAnalysisLogs
      ArtifactName: CodeAnalysisLogs
