pipelines:
  default:
    - step:
        script:
          - export SNYK_API=https://api.eu.snyk.io
          - pipe: snyk/snyk-scan:0.5.2
            variables:
              SNYK_TOKEN: $SNYK_TOKEN_EU
              LANGUAGE: 'npm'
              DONT_BREAK_BUILD: 'TRUE'
              SEVERITY_THRESHOLD: 'high'
              CODE_INSIGHTS_RESULTS: 'TRUE'
              MONITOR: 'TRUE'
              ORGANIZATION: 'bb32cc43-ec07-4f8c-93da-c82194615ac2'
              DEBUG: 'TRUE'
              EXTRA_ARGS: "--all-projects"
