pipelines:
  default:
    - step:
        script:
          - pipe: snyk/snyk-scan:0.7.0
            variables:
              SNYK_TOKEN: '$SNYK_TOKEN_EU'
              LANGUAGE: 'npm'
              DONT_BREAK_BUILD: 'true'
              SEVERITY_THRESHOLD: 'high'
              CODE_INSIGHTS_RESULTS: 'false'
              MONITOR: 'false'
              ORGANIZATION: 'bb32cc43-ec07-4f8c-93da-c82194615ac2'
              DEBUG: 'true'
              SNYK_API: 'https://api.eu.snyk.io'
              EXTRA_ARGS: "--all-projects"
