name: Snyk
on: push
jobs:
  snyk-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install Snyk
      run: npm install -g snyk snyk-to-html
    - name: Run Snyk Code
      run: |
        snyk code test --sarif-file-output=report.sarif
        SC_RET_CODE=$?
        snyk-to-html -o report.html < report.sarif
        exit $SC_RET_CODE
    - uses: actions/upload-artifact@v3
      with:
        name: snyk-code-report
        path: report.html


  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Build a Docker image
    #   run: docker build -t sebsnyk/juice-shop .
    - name: Run Snyk to check Docker image for vulnerabilities
      # Snyk can be used to break the build when it detects vulnerabilities.
      # In this case we want to upload the issues to GitHub Code Scanning
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        # In order to use the Snyk Action you will need to have a Snyk API token.
        # More details in https://github.com/snyk/actions#getting-your-snyk-token
        # or you can signup for free at https://snyk.io/login
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: sebsnyk/juice-shop
        args: --org=e-corp --file=Dockerfile 
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif

