name: Example workflow for Snyk

on: push

jobs:

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_API: ${{ secrets.SNYK_API }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects

  code-scan:
    # Configure Environment
    name: 'Snyk Code Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          snyk auth ${SNYK_TOKEN}
      # Run Snyk Code
      - name: Run Snyk Code
        run: |
          snyk code test --sarif  > results.sarif
        continue-on-error: true
      - name: Upload SARIF file
        run: |
          DATA=gzip -c analysis-data.sarif | base64 -w0
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/sebsnyk/juice-shop/code-scanning/sarifs \
            -d "{\"commit_sha\":\"${GITHUB_SHA}\",\"ref\":\"${GITHUB_REF}\",\"sarif\":\"${DATA}\"}"
  